stages:
- build
- test

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  artifacts:
    paths:
      - target/*
  script:
    - dotnet publish -c Release ./MergeApplication/MergeApplication.csproj -o "./target"

unittests:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet test -c Release ./MergeApplicationTests/MergeApplicationTests.csproj
